name: rlm_server
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - rdkit
dependencies:
  - flask=1.1.2
  - hyperopt=0.2.4
  - ipython=7.16.1
  - numpy=1.18
  - pandas=1.1.3
  - pip=20.0
  - python>=3.7
  - rdkit=2020.03
  - scikit-learn=0.22
  - tensorboardX=2.1
  - tqdm=4.48.0
  - networkx=2.4
  - pytorch=1.6.0
  - torchvision=0.7.0
  - typing-extensions=3.7.4.2
  - pip:
    - tensorflow==2.2.0
    - keras-self-attention==0.41.0
    - typed-argument-parser==1.5.4
    - torch
    - requests
    - werkzeug
    - FPSim2
    - flask_swagger_ui==4.11.1
    - py-healthcheck==1.10.1

